import { chmod, writeFile } from "node:fs/promises"
import { userInfo } from "node:os"
import { dirname } from "node:path"
import { rampMode, type Ramp } from "./host-palette.ts"
import { ensurePrivateDirectories } from "./private-directory.ts"

/** The theme id the extension registers and `--theme` selects. */
export const HUNK_THEME_ID = "fmx"
/** The Ramp the extension paints from, as JSON, in hunk's environment. */
export const HUNK_RAMP_ENV_VAR = "FMX_RAMP"

/**
 * fx's own diff markers (fxnk `style/tokens.json` `diff_markers`), identical
 * on a light and a dark canvas. Inside the diff these are the only two hues
 * besides the Ramp's focus blue, and each means exactly one thing.
 */
export const DIFF_ADDED_COLOR = "#30a46c"
export const DIFF_REMOVED_COLOR = "#e5484d"

/**
 * The Ramp fmx hands the extension, plus which column of fx's grays it came
 * from. `mode` chooses the built-in hunk theme whose syntax highlighting is
 * inherited; fmx never overrides `syntaxScopes`, so code stays readable.
 */
export type HunkRamp = Ramp & { mode: "dark" | "light" }

export function hunkRampValue(ramp: Ramp): string {
  return JSON.stringify({ ...ramp, mode: rampMode(ramp) } satisfies HunkRamp)
}

/**
 * Where the extension is written. `/tmp/fmx-<uid>` is fmx's own private
 * directory — generated code does not belong in a configuration directory a
 * human reads, and a file here cannot outlive the sessions that import it.
 */
export function hunkThemeExtensionPath(uid: number = userInfo().uid): string {
  return `/tmp/fmx-${uid}/hunk-theme.js`
}

/**
 * Write the extension where hunk can import it, replacing whatever is there.
 *
 * fmx is compiled to a single binary, so the extension has to exist as a real
 * file for hunk's `await import()` to reach it. Rewriting it on every start is
 * what makes fmx the sole author of its content: an edited copy never
 * survives, and the file's directory is private to this user.
 */
export async function materializeHunkThemeExtension(
  path: string = hunkThemeExtensionPath(),
): Promise<string> {
  await ensurePrivateDirectories([dirname(path)], "hunk theme")
  await writeFile(path, HUNK_THEME_EXTENSION_SOURCE, { mode: 0o600 })
  // `mode` applies only where the file is created, and this one is rewritten
  // on every start: say it again so a file left behind loosely cannot stay so.
  await chmod(path, 0o600)
  return path
}

/**
 * The extension hunk loads, as plain JavaScript so nothing has to transpile it.
 *
 * It runs inside hunk, reads the Ramp out of its own environment, and
 * registers one theme. A `--extension` path is discovered with origin `flag`,
 * which hunk's repository-trust gate does not cover, so loading it asks the
 * human nothing. If the Ramp is missing or malformed the extension registers
 * nothing and hunk falls back to its own theme, because an unknown `--theme`
 * id resolves to hunk's default rather than failing.
 *
 * Only the slots below are set. The neutral surfaces are also cleared by
 * `--transparent-bg`, which paints them as the terminal's default background:
 * fmx forwards the host palette into the panel's terminal and re-forwards it
 * on a live theme change, so those surfaces follow the host's theme while
 * hunk runs. Everything given a hex here is fixed until the panel re-opens.
 */
export const HUNK_THEME_EXTENSION_SOURCE = `// Generated by fmx. Rewritten on every start; edits do not survive.
const ADDED = ${JSON.stringify(DIFF_ADDED_COLOR)}
const REMOVED = ${JSON.stringify(DIFF_REMOVED_COLOR)}
// A diff row carries its sign's hue at a fraction of full strength; the
// word-diff span inside it carries the same hue one step louder. Both are
// mixed with the host's own background, so a light canvas needs no second set.
const ROW_TINT = 0.14
const WORD_TINT = 0.28
const HEX = /^#[0-9a-f]{6}$/i

function mix(base, tint, amount) {
  const channel = (offset) => {
    const from = parseInt(base.slice(offset, offset + 2), 16)
    const to = parseInt(tint.slice(offset, offset + 2), 16)
    return Math.round(from + (to - from) * amount)
      .toString(16)
      .padStart(2, "0")
  }
  return "#" + channel(1) + channel(3) + channel(5)
}

function readRamp() {
  const raw = process.env[${JSON.stringify(HUNK_RAMP_ENV_VAR)}]
  if (!raw) return null
  let parsed
  try {
    parsed = JSON.parse(raw)
  } catch {
    return null
  }
  if (!parsed || typeof parsed !== "object") return null
  // Every slot hunk is given must be a #rrggbb literal: it validates each one
  // and drops the whole theme's field otherwise, which would leak the base
  // theme's GitHub colors into a surface fmx claims to own.
  for (const key of ["background", "surface", "divider", "dim", "secondary", "foreground", "focus"]) {
    if (typeof parsed[key] !== "string" || !HEX.test(parsed[key])) return null
  }
  return parsed
}

export default function (hunk) {
  const ramp = readRamp()
  if (!ramp) return
  const background = ramp.background
  hunk.registerTheme({
    id: ${JSON.stringify(HUNK_THEME_ID)},
    label: "fmx",
    // Inherited for its syntax highlighting alone; every other slot is set below.
    base: ramp.mode === "light" ? "github-light-default" : "github-dark-default",

    // Neutral surfaces: the Ramp, and what --transparent-bg replaces with the
    // host's own background so they follow a live theme change.
    background,
    panel: ramp.surface,
    panelAlt: ramp.surface,
    contextBg: background,
    contextContentBg: background,
    lineNumberBg: background,
    border: ramp.divider,
    text: ramp.foreground,
    muted: ramp.dim,
    lineNumberFg: ramp.dim,

    // Selection is the Ramp's one blue and its raised fill, never a diff hue.
    accent: ramp.focus,
    accentMuted: ramp.surface,
    selectedHunk: ramp.surface,

    // The diff's two hues. The sign is full strength; the row and the
    // word-diff span are the same hue mixed toward the host's background.
    addedSignColor: ADDED,
    removedSignColor: REMOVED,
    addedBg: mix(background, ADDED, ROW_TINT),
    movedAddedBg: mix(background, ADDED, ROW_TINT),
    removedBg: mix(background, REMOVED, ROW_TINT),
    movedRemovedBg: mix(background, REMOVED, ROW_TINT),
    addedContentBg: mix(background, ADDED, WORD_TINT),
    removedContentBg: mix(background, REMOVED, WORD_TINT),

    // A count of added and removed lines is the same semantic as a sign, so it
    // takes the same hue. Everything that is not add-or-remove stays gray.
    badgeAdded: ADDED,
    badgeRemoved: REMOVED,
    badgeNeutral: ramp.dim,
    fileNew: ADDED,
    fileDeleted: REMOVED,
    fileModified: ramp.secondary,
    fileRenamed: ramp.secondary,
    fileUntracked: ramp.dim,

    // A note is a surface that takes keys: the Ramp's focus border over its fill.
    noteBorder: ramp.focus,
    noteBackground: ramp.surface,
    noteTitleBackground: ramp.surface,
    noteTitleText: ramp.foreground,
  })
}
`
